apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-pipeline-pull-request
spec:
  params:
    - name: repo_url
      type: string
      default: https://github.com/konflux-ci/namespace-lister/
    - name: revision
      type: string
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
      params:
        - name: url
          value: $(params.repo_url)
        - name: revision
          value: $(params.revision)
        - name: depth
          value: "0"
    - name: golangci-lint
      runAfter:
        - fetch-repository
      taskSpec:
        steps:
          - image: registry.redhat.io/openshift4/ose-cli:latest
            script: |
              dnf install -y golang
              make lint
  timeouts:
    pipeline: "1h"
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
